theme: architect
title: George Aalbers
author: George Aalbers
email: h.j.g.aalbers@uvt.nl
description: > # this means to ignore newlines until "baseurl:"
  Machine learning and time-series statistical analysis.

# social links
twitter_username: GeorgeAalbers # DO NOT include the @ character, or else the build will fail!
github_username:  george-aalbers # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
